import dayjs from 'dayjs';

export const formInitialValues = {
  maxSupply: 0,
  limitSupply: 0,
  mintPrice: '',
  name: '',
  hashtag: '',
  creatorName: '',
  creatorAddress: '',
  description: '',
  thumbnail: '',
  thirdPartyScripts: [],
  scripts: [''],
  reservationList: [' '],
  mintFee: 0,
  fromWalletAddress: '',
  openMintUnixTimestamp: dayjs().unix(),
  tokenDescription: '',
  styles: '',
  royalty: 0,
  socialWeb: '',
  socialTwitter: '',
  socialDiscord: '',
  socialMedium: '',
  socialInstagram: '',
  license: 'MIT',
  mintTokenAddress: '',
};
