export const formInitialValues = {
  maxSupply: 0,
  limitSupply: 0,
  mintPrice: '',
  name: '',
  creatorName: '',
  creatorAddress: '',
  description: '',
  thumbnail: '',
  thirdPartyScripts: [' '],
  scripts: [' '],
  reservationList: [' '],
  mintFee: 0,
  fromWalletAddress: '',
  openMintUnixTimestamp: 0,
  tokenDescription: '',
  styles: '',
  royalty: 0,
  socialWeb: '',
  socialTwitter: '',
  socialDiscord: '',
  socialMedium: '',
  socialInstagram: '',
  license: '',
  mintTokenAddress: '',
};
