export enum SandboxFileError {
  UNKNOWN = 'UNKNOWN',
  WRONG_FORMAT = 'WRONG_FORMAT',
  NO_INDEX_HTML = 'NO_INDEX_HTML',
  NO_SNIPPET = 'NO_SNIPPET',
  NO_REQUIRED_LIB = 'NO_REQUIRED_LIB',
  FAILED_UNZIP = 'FAILED_UNZIP',
}
