export enum SandboxFileError {
  UNKNOWN = 'UNKNOWN',
  WRONG_FORMAT = 'WRONG_FORMAT',
  NO_INDEX_HTML = 'NO_INDEX_HTML',
  NO_SNIPPET_CONTRACT = 'NO_SNIPPET_CONTRACT',
  NO_SNIPPET_RANDOM = 'NO_SNIPPET_RANDOM',
  NO_REQUIRED_LIB = 'NO_REQUIRED_LIB',
  FAILED_UNZIP = 'FAILED_UNZIP',
}
