export enum SandboxSWEventType {
  REGISTER_URLS = 'REGISTER_URLS',
  REGISTER_REFERRER = 'REGISTER_REFERRER',
  REGISTER_HTML = 'REGISTER_HTML',
  GET_INDEX = 'GET_INDEX',
  INDEX_HTML_CONTENTS = 'INDEX_HTML_CONTENTS',
}
