export enum WalletError {
  UNSUPPORTED_CHAIN = 'UNSUPPORTED_CHAIN',
  FAILED_SWITCH_CHAIN = 'FAILED_SWITCH_CHAIN',
  FAILED_ADD_CHAIN = 'FAILED_ADD_CHAIN',
  FAILED_CONNECT = 'FAILED_CONNECT',
  NO_INSTANCE = 'NO_INSTANCE',
  FAILED_LINK_WALLET = 'FAILED_LINK_WALLET',
  FAILED_UNLINK_WALLET = 'FAILED_UNLINK_WALLET',
  FAILED_SIGN_MESSAGE = 'FAILED_SIGN_MESSAGE',
}
