import { Chain } from '@interfaces/chain';

export const EVM_CHAINS: Array<Chain> = [
  {
    name: 'Ethereum',
    shortName: 'eth',
    chainID: 1,
    testnet: false,
    currency: 'ETH',
    scanUrl: 'https://etherscan.io',
    rpcUrl: 'https://mainnet.infura.io/v3/6fcfb74bf71f4c3e92372d86eb947f43',
    openseaAssetUrl: 'https://opensea.io/assets/ethereum',
    iconUrl: 'https://cdn.rove.to/icons/ethereum-eth-logo.svg',
    faucet: '',
  },
  {
    name: 'Goerli',
    shortName: 'goerli',
    chainID: 5,
    testnet: true,
    currency: 'GoerliETH',
    scanUrl: 'https://goerli.etherscan.io/',
    rpcUrl: 'https://goerli.infura.io/v3',
    openseaAssetUrl: 'https://testnets.opensea.io/assets/goerli',
    iconUrl: 'https://cdn.rove.to/icons/ethereum-eth-logo.svg',
    faucet: 'https://goerlifaucet.com/',
  },
  {
    name: 'Polygon',
    shortName: 'polygon',
    chainID: 137,
    testnet: false,
    currency: 'MATIC',
    scanUrl: 'https://polygonscan.com',
    rpcUrl: 'https://polygon-rpc.com',
    openseaAssetUrl: 'https://opensea.io/assets/matic',
    iconUrl: 'https://cdn.rove.to/icons/polygon-matic-logo.svg',
    faucet: '',
  },
  {
    name: 'Mumbai',
    shortName: 'mumbai',
    chainID: 80001,
    testnet: true,
    currency: 'MATIC',
    scanUrl: 'https://mumbai.polygonscan.com',
    rpcUrl: 'https://matic-mumbai.chainstacklabs.com',
    openseaAssetUrl: 'https://testnets.opensea.io/assets/mumbai',
    iconUrl: 'https://cdn.rove.to/icons/polygon-matic-logo.svg',
    faucet: 'https://mumbaifaucet.com/',
  },
];
