import { Chain } from '@interfaces/chain';

export const EVM_CHAINS: Array<Chain> = [
  {
    name: 'Goerli',
    shortName: 'goerli',
    chainID: '5',
    testnet: true,
    currency: 'GoerliETH',
    scanUrl: 'https://goerli.etherscan.io/',
    rpcUrl: 'https://goerli.infura.io/v3',
    openseaAssetUrl: 'https://testnets.opensea.io/assets/goerli',
    iconUrl: 'https://cdn.rove.to/icons/ethereum-eth-logo.svg',
  },
  {
    name: 'Mumbai',
    shortName: 'mumbai',
    chainID: '80001',
    testnet: true,
    currency: 'MATIC',
    scanUrl: 'https://mumbai.polygonscan.com',
    rpcUrl: 'https://matic-mumbai.chainstacklabs.com',
    openseaAssetUrl: 'https://testnets.opensea.io/assets/mumbai',
    iconUrl: 'https://cdn.rove.to/icons/polygon-matic-logo.svg',
  },
  {
    name: 'Fantom Testnet',
    shortName: 'fantom%20testnet',
    chainID: '4002',
    testnet: true,
    currency: 'FTM',
    scanUrl: 'https://testnet.ftmscan.com',
    rpcUrl: 'https://rpc.testnet.fantom.network',
    openseaAssetUrl: 'https://testnets.opensea.io/assets/fantom',
    iconUrl: 'https://cdn.rove.to/icons/fantom-ftm-logo.svg',
  },
  {
    name: 'BSC Testnet',
    shortName: 'bsc/testnet',
    chainID: '97',
    testnet: true,
    currency: 'tBNB',
    scanUrl: 'https://testnet.bscscan.com',
    rpcUrl: 'https://data-seed-prebsc-2-s2.binance.org:8545',
    openseaAssetUrl: 'https://testnets.opensea.io/assets/bsc_testnet',
    iconUrl: 'https://cdn.rove.to/icons/bnb-bnb-logo.svg',
  },
  {
    name: 'Harmony Testnet',
    shortName: 'harmony',
    chainID: '1666700000',
    testnet: true,
    currency: 'ONE',
    scanUrl: 'https://testnet.bscscan.com',
    rpcUrl: 'https://api.s0.b.hmny.io',
    openseaAssetUrl: 'https://testnets.opensea.io/assets/harmony',
    iconUrl: 'https://cdn.rove.to/icons/harmony-one-logo.svg',
  },
  {
    name: 'Ethereum',
    shortName: 'eth',
    chainID: '1',
    testnet: false,
    currency: 'ETH',
    scanUrl: 'https://etherscan.io',
    rpcUrl: 'https://mainnet.infura.io/v3/6fcfb74bf71f4c3e92372d86eb947f43',
    openseaAssetUrl: 'https://opensea.io/assets/ethereum',
    iconUrl: 'https://cdn.rove.to/icons/ethereum-eth-logo.svg',
  },
  {
    name: 'Polygon',
    shortName: 'polygon',
    chainID: '137',
    testnet: false,
    currency: 'MATIC',
    scanUrl: 'https://polygonscan.com',
    rpcUrl: 'https://polygon-rpc.com',
    openseaAssetUrl: 'https://opensea.io/assets/matic',
    iconUrl: 'https://cdn.rove.to/icons/polygon-matic-logo.svg',
  },
  {
    name: 'Fantom',
    shortName: 'fantom',
    chainID: '250',
    testnet: false,
    currency: 'FTM',
    scanUrl: 'https://ftmscan.com',
    rpcUrl: 'https://rpc.ftm.tools',
    openseaAssetUrl: 'https://opensea.io/assets/fantom',
    iconUrl: 'https://cdn.rove.to/icons/fantom-ftm-logo.svg',
  },
  {
    name: 'BSC',
    shortName: 'bsc',
    chainID: '56',
    testnet: false,
    currency: 'BNB',
    scanUrl: 'https://bscscan.com',
    rpcUrl: 'https://bsc-dataseed3.ninicoin.io',
    openseaAssetUrl: 'https://opensea.io/assets/bsc',
    iconUrl: 'https://cdn.rove.to/icons/bnb-bnb-logo.svg',
  },
  {
    name: 'Harmony',
    shortName: 'harmony',
    chainID: '1666600000',
    testnet: false,
    currency: 'ONE',
    scanUrl: 'https://explorer.harmony.one',
    rpcUrl: 'https://api.harmony.one',
    openseaAssetUrl: 'https://opensea.io/assets/harmony',
    iconUrl: 'https://cdn.rove.to/icons/harmony-one-logo.svg',
  },
  {
    name: 'Kardiachain',
    shortName: 'Kai',
    chainID: '24',
    testnet: false,
    currency: 'KAI',
    scanUrl: 'https://explorer.kardiachain.io',
    rpcUrl: 'https://rpc.kardiachain.io',
    openseaAssetUrl: 'https://opensea.io/assets/harmony',
    iconUrl: 'https://cdn.rove.to/icons/kai-icon.png',
  },
];
